[package]
name = "in_inscribing"
version = "0.1.0"
authors = ["Qfwfq <notkrd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
